name: gpdb-solo

releases:
  - name: database
    version: latest

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: db
    instances: 1
    lifecycle: errand
    vm_type: small
    networks:
      - name: internal
    jobs:
      - name: noop
        release: database
    azs:
      - z1
    stemcell: default

update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 3000-27000
  update_watch_time: 3000-27000

director_uuid: 2db63f0d-b544-456a-b923-86c1e689fcc9
